/* Assignment 4 cte and normalisation

 -- que 1  Identify a table in the Sakila database that violates 1NF. Explain how you would normalize it to achieve 1NF

-- Ans 1 .  Actor_award table violate nf1 formation in mavenmovies database violate 1nf formation we can normalised it by updating 
-- the actor_award table , avoid multivalued (each column has only atomic values) , Also we can create seperate tables for the
--  columns which contain multiple values etc 
select awards from actor_award ;

-- que 2 Choose a table in Sakila and describe how you would determine whether it is in 2NF. If it violates 2NF, 
-- explain the steps to normalize it 
 
select * from film ; 
-- ans 2 film table from sakila databse violates 2nf because of the special features column special feature column on the
--  table violate 1nf and 2nf has a rule that table is in 1nf 
-- Identify Partial Dependencies: all the non-prime attributes like title , discription , release_year etc are fully dependent on the primary key
-- which is film id 
-- we can create a another table and make them columns foreign keys and these foreign keys make reference to that film id table 
-- by using these steps we can avoid 2 nf .


-- que 3 Identify a table in Sakila that violates 3NF. Describe the transitive dependencies present and outline the 
-- steps to normalize the table to 3NF
 ans if we saw the customer table in the sakila database we get to know that the column name address_id is linked with store id
and both are non key attribute  and 3nf stays that table is in 2 nf from and it ensure that all the non key attribute column on the
 table are not related with each other (one non key attribute column related to other non key attribute column) so because of that it 
 violate 2 and 3 nf 

steps to prevent 3nf 

1, analyse the violation 
2, create new table to store data 
3 , update customer table (make store id as foreign key )
4 , update address info. (so it reference to the foreign key )
etc 
*/
-- qur 5 Write a query using a CTE to retrieve the distinct list of actor names and the number of films they have acted in from the  actor
-- and  film_actor tables

-- ans 
WITH ActorFilmCount AS (
    SELECT
        a.actor_id,
        CONCAT(a.first_name, ' ', a.last_name) AS actor_name,
        COUNT(fa.film_id) AS film_count
    FROM
        actor a
    JOIN
        film_actor fa ON a.actor_id = fa.actor_id
    GROUP BY
        a.actor_id, actor_name
)

SELECT
    actor_name,
    film_count
FROM
    ActorFilmCount
ORDER BY
    film_count DESC, actor_name ; 

-- que 6 Use a recursive CTE to generate a hierarchical list of categories and their subcategories from the category table in Sakila
-- ans 
WITH RECURSIVE CategoryHierarchy AS (
    SELECT
        c.category_id,
        c.name AS category_name,
        NULL AS parent_category_id,
        0 AS level
    FROM
        category c
    WHERE
        NOT EXISTS (
            SELECT 1
            FROM film_category fc
            WHERE fc.category_id = c.category_id
        )

    UNION ALL

    SELECT
        c.category_id,
        c.name AS category_name,
        fc.category_id AS parent_category_id,
        ch.level + 1 AS level
    FROM
        category c
    JOIN
        film_category fc ON c.category_id = fc.category_id
    JOIN
        CategoryHierarchy ch ON fc.film_id = ch.category_id
)

SELECT
    category_id,
    category_name,
    parent_category_id,
    level
FROM
    CategoryHierarchy
ORDER BY
    level, category_id ; 
    
-- que 7 Create a CTE that combines information from the  film and language tables to display the films title , language ,  rental rate
-- ans
 WITH FilmLanguageInfo AS (
    SELECT
        f.title AS film_title,
        l.name AS language,
        f.rental_rate
    FROM
        film f
    JOIN
        language l ON f.language_id = l.language_id
)

SELECT
    film_title,
    language,
    rental_rate
FROM
    FilmLanguageInfo;
    
    -- que 8  Write a query using a CTE to find the total revenue generated by each customer (sum of payments) from customer and payment table 
    
-- ans 
WITH CustomerRevenue AS (
    SELECT
        c.customer_id,
        c.first_name || ' ' || c.last_name AS customer_name,
        SUM(p.amount) AS total_revenue
    FROM
        customer c
    LEFT JOIN
        payment p ON c.customer_id = p.customer_id
    GROUP BY
        c.customer_id, customer_name
)

SELECT
    customer_id,
    customer_name,
    COALESCE(total_revenue, 0) AS total_revenue
FROM
    CustomerRevenue
ORDER BY
    total_revenue DESC;

-- que 9 Utilize a CTE with a window function to rank films based on their rental duration from the  film table

-- ans 
WITH RankedFilms AS (
    SELECT
        film_id,
        title,
        rental_duration,
        RANK() OVER (ORDER BY rental_duration DESC) AS rental_duration_rank
    FROM
        film
)

SELECT
    film_id,
    title,
    rental_duration,
    rental_duration_rank
FROM
    RankedFilms
ORDER BY
    rental_duration_rank;

-- que 10  Create a CTE to list customers who have made more than two rentals, and then join this CTE with the customer table to retrieve additional 
-- customer details
-- ans
 WITH CustomerRentals AS (
    SELECT
        customer_id,
        COUNT(rental_id) AS rental_count
    FROM
        rental
    GROUP BY
        customer_id
    HAVING
        COUNT(rental_id) > 2
)

SELECT
    c.*,
    cr.rental_count
FROM
    customer c
JOIN
    CustomerRentals cr ON c.customer_id = cr.customer_id
ORDER BY
    cr.rental_count DESC;

-- que 11 Write a query using a CTE to find the total number of rentals made each month, considering the  rental date from the rental table 
-- ans 
WITH MonthlyRentals AS (
    SELECT
        DATE_FORMAT(rental_date, '%Y-%m') AS rental_month,
        COUNT(rental_id) AS total_rentals
    FROM
        rental
    GROUP BY
        rental_month
)

SELECT
    rental_month,
    total_rentals
FROM
    MonthlyRentals
ORDER BY
    rental_month;

-- que 12 Use a CTE to pivot the data from the  payment rental_date table to display the total payments made by each customer in 
-- separate columns for different payment methods
-- ans since we dont have payment method column or any  column that specify payment type we calculate total payments made by each customer 

WITH CustomerPayments AS (
    SELECT
        customer_id,
        SUM(amount) AS total_payments
    FROM
        payment
    GROUP BY
        customer_id
)

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    cp.total_payments
FROM
    customer c
JOIN
    CustomerPayments cp ON c.customer_id = cp.customer_id;

-- que 13 Create a CTE to generate a report showing pairs of actors who have appeared in the same film together, using the film_actor 
-- table 
-- ans 
WITH ActorPairs AS (
    SELECT
        fa1.actor_id AS actor1_id,
        fa2.actor_id AS actor2_id,
        COUNT(*) AS films_together
    FROM
        film_actor fa1
        JOIN film_actor fa2 ON fa1.film_id = fa2.film_id AND fa1.actor_id < fa2.actor_id
    GROUP BY
        fa1.actor_id, fa2.actor_id
    HAVING
        COUNT(*) > 0
)

SELECT
    ap.actor1_id,
    ap.actor2_id,
    ap.films_together
FROM
    ActorPairs ap;
    
    -- que 14 Implement a recursive CTE to find all employees in the staff table who report to a specific manager,
   select * from staff ; 
-- ans 

